### ISSUE TITLE
Support fastify v2

### ISSUE THREAD

**Issue by blacksmoke26** [smartiniOnGitHub/fastify-favicon#6]
In `package.json`
```json
"fastify": "^2.0.0",
...
"fastify-no-icon": "^2.0.0",
```

Got error:
```
For help, see: https://nodejs.org/en/docs/inspector
G:\WebData\wwwroot\projects\thai-condos\foundation\api\node_modules\fastify-no-icon\node_modules\fastify-plugin\index.js:47
    throw new Error(`fastify-plugin - expected '${version}' fastify version, '${fastifyVersion}' is installed`)
    ^

Error: fastify-plugin - expected '^1.1.0' fastify version, '2.0.0' is installed
    at checkVersion (G:\WebData\wwwroot\projects\thai-condos\foundation\api\node_modules\fastify-no-icon\node_modules\fastify-plugin\index.js:47:11)
    at plugin (G:\WebData\wwwroot\projects\thai-condos\foundation\api\node_modules\fastify-no-icon\node_modules\fastify-plugin\index.js:25:5)
    at Object.<anonymous> (G:\WebData\wwwroot\projects\thai-condos\foundation\api\node_modules\fastify-no-icon\plugin.js:14:18)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at module.exports (G:\WebData\wwwroot\projects\thai-condos\foundation\api\node\components\fastify\init-server.js:87:13)
    at Object.<anonymous> (G:\WebData\wwwroot\projects\thai-condos\foundation\api\node\server.js:16:62)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by smartiniOnGitHub** [comment]
Hi, sorry but I think you are using 'fastify-no-icon' and not this module ('fastify-favicon'), right ?
Anyway don't worry; looking at its code it seems it still requires Fastify 1.x, see [here](https://github.com/jsumners/fastify-no-icon/blob/master/package.json), but should be a quick fix.
Tell me if you need some help to do. Or in the meantime you could use this plugin :-) .
Bye

**Comment by blacksmoke26** [comment]
Ah sorry! My bad! :+1:

**Comment by blacksmoke26** [comment]
Removed previous plugin and used your one, works great. Thank you!

```
//<editor-fold desc="General Plugins">
.register(require('fastify-favicon')) // <--- here
.register(require('fastify-accepts'))
.register(require('fastify-cookie'))
.after(err => {
  if (err) throw err
})
//</editor-fold>
```
