### ISSUE TITLE
fastify 3

### ISSUE THREAD

**Issue by borodadada** [smartiniOnGitHub/fastify-favicon#8]
```
throw new Error(`fastify-plugin: ${pluginName} - expected '${version}' fastify version, '${fastifyVersion}' is installed`)
    ^

Error: fastify-plugin: fastify-favicon - expected '^2.0.0' fastify version, '3.0.0' is installed
    at checkVersion (D:\js\test\node_modules\fastify-plugin\index.js:67:11)
    at plugin (D:\js\test\node_modules\fastify-plugin\index.js:36:5)
    at Object.<anonymous> (D:\js\test\node_modules\fastify-favicon\src\plugin.js:48:18)
```
hello, error

**Comment by smartiniOnGitHub** [comment]
Hi, sorry for this but the plugin is compatible with Fastify 2.x at the moment; a new plugin release (3.0.0) will be made soon to have it compatible with latest Fastify 3.x . Bye
